---
# tasks file for pyenv
- name: Create directories
  file:
    dest: "{{ pyenv_root | dirname }}"
    state: directory
- name: Clone pyenv repository
  git:
    repo: "{{ pyenv_repo }}"
    dest: "{{ pyenv_root }}"
    version: "{{ pyenv_version }}"
    update: "{{ pyenv_update }}"
- block:
  - name: Add configurations to ~/.bashrc, ~/.profile, or ~/.zshrc or etc
    lineinfile:
      dest: "{{ pyenv_rc_path }}"
      line: 'export PYENV_ROOT="{{ pyenv_root }}"'
      regexp: '^export PYENV_ROOT='
      create: yes
  - name: Add configurations to ~/.bashrc, ~/.profile, or ~/.zshrc or etc
    lineinfile:
      dest: "{{ pyenv_rc_path }}"
      line: 'export PATH="$PYENV_ROOT/bin:$PATH"'
      regexp: '^\s*export\s*PATH="?\$PYENV_ROOT/bin:\$PATH"?'
      create: yes
  - name: Add configurations to ~/.bashrc, ~/.profile, or ~/.zshrc or etc
    lineinfile:
      dest: "{{ pyenv_rc_path }}"
      line: 'eval "$(pyenv init -)"'
      create: yes
  when: pyenv_rc_path != "NOT ADD"
- include: "{{ pyenv_os_families.get(ansible_os_family, 'default') }}.yml"
  static: no
  when: pyenv_is_dependencies_installed and ansible_os_family in pyenv_os_families
